namespace Basora.Core.Models.Metadata;

/// <summary>How a column generates its own values, if it does.</summary>
public enum IdentityKind
{
    /// <summary>The column has no identity or serial behaviour.</summary>
    None,

    /// <summary><c>GENERATED ALWAYS AS IDENTITY</c>. A supplied value is rejected without <c>OVERRIDING</c>.</summary>
    Always,

    /// <summary><c>GENERATED BY DEFAULT AS IDENTITY</c>. A supplied value wins.</summary>
    ByDefault,

    /// <summary>
    /// The older <c>serial</c> pattern: an integer column defaulting to a sequence.
    /// Not an identity column, and worth showing differently because it behaves
    /// differently when the table is copied or the default is dropped.
    /// </summary>
    Serial,
}
